/**
 * Dialogue accessor — single source of truth between rendered bubble text
 * and the MP3 filenames generated by scripts/generate-voice.ts.
 *
 * Components call `renderLine(key, { name })` to get the user-facing string.
 * The AudioEngine plays the matching MP3 from /public/audio/<key>.mp3 (or
 * the A/B split for {{NAME}}-bearing lines) using the same key.
 *
 * Keep these names in sync — adding a key here means re-running
 * `npm run generate-voice` to produce the matching MP3.
 */

import dialogueData from "./dialogue.json";

export type DialogueKey = keyof typeof dialogueData.lines;

export const NAME_PLACEHOLDER = "{{NAME}}";

export function getLine(key: DialogueKey): string {
  return dialogueData.lines[key];
}

export function lineHasNameSlot(key: DialogueKey): boolean {
  return getLine(key).includes(NAME_PLACEHOLDER);
}

export interface RenderVars {
  name?: string | null;
}

/**
 * Substitutes {{NAME}} in the line. Throws if a line needs a name and none
 * was supplied — that's a programmer error, not a runtime fallback case.
 */
export function renderLine(key: DialogueKey, vars: RenderVars = {}): string {
  const raw = getLine(key);
  if (!raw.includes(NAME_PLACEHOLDER)) return raw;
  if (!vars.name) {
    throw new Error(
      `renderLine("${key}") needs a name but none was supplied`,
    );
  }
  return raw.split(NAME_PLACEHOLDER).join(vars.name);
}
